ALTER TABLE  `inf` CHANGE  `INF_NAME`  `INF_NAME` VARCHAR( 256 ) CHARACTER SET utf8 COLLATE utf8_bin NULL;
ALTER TABLE  `inf` CHANGE  `INF_TYPE`  `INF_TYPE` INT( 11 ) NOT NULL DEFAULT  '1' COMMENT  '1 - INTERNAL, 2 - EXTERNAL, 3 - INLINE';
ALTER TABLE  `prj` ADD  `PRJ_SHORT_DESCRIPTION` VARCHAR( 256 ) NULL AFTER  `PRJ_DESCRIPTION`;
ALTER TABLE  `prj` ADD  `PRJ_NAME` VARCHAR( 256 ) NOT NULL DEFAULT  ' ' AFTER  `PRJ_ID`;

UPDATE `inf` SET  `INF_NAME` =  'Adres siedziby/biura/miejsca działalności' WHERE  `inf`.`INF_ID` = 2;
UPDATE `inf` SET  `INF_NAME` = NULL WHERE  `inf`.`INF_ID` = 17;
UPDATE `inf` SET  `INF_NAME` = NULL WHERE  `inf`.`INF_ID` = 11;
UPDATE `inf` SET  `INF_NAME` = NULL WHERE  `inf`.`INF_ID` = 27;
UPDATE `inf` SET  `INF_SHOW_FILE_CAT` =  '2' WHERE  `inf`.`INF_ID` = 28;
DELETE FROM `inf` WHERE `inf`.`INF_ID` = 29;