DELETE FROM `sit` WHERE `sit`.`SIT_NAME` = 'Oferta';

SELECT * FROM `inf` where `INF_SIT_ID` in (6,10) or `INF_NAME` = 'Zbiórki publiczne';
UPDATE `inf` SET `INF_OBLIGATORY` = 0, `INF_MODIFY_DATE` = '2013-02-24 12:53:00', `INF_MODIFY_BY` = 1 where `INF_SIT_ID` in (6,10) or `INF_NAME` = 'Zbiórki publiczne';

ALTER TABLE  `nws` ADD  `NWS_BIP` BOOLEAN NOT NULL DEFAULT  '0';

ALTER TABLE  `inf` ADD  `INF_SHOW_CTRL` BOOLEAN NOT NULL DEFAULT  '0' AFTER  `INF_SHOW_FIN_TYPE`;

UPDATE `inf` SET  `INF_CONTENT` =  '',
`INF_SHOW_CTRL` =  '1' , `INF_OBLIGATORY` = '0'
WHERE  `inf`.`INF_SIT_ID` = 10;


SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
--
-- Struktura tabeli dla  `ctrl`
--

CREATE TABLE IF NOT EXISTS `ctrl` (
  `CTRL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CTRL_YEAR` int(11) NOT NULL,
  `CTRL_NAME` varchar(128) COLLATE utf8_bin NOT NULL,
  `CTRL_INSTITUTION` varchar(128) COLLATE utf8_bin NOT NULL,
  `CTRL_DATE_START` date NOT NULL,
  `CTRL_DATE_END` date NOT NULL,
  `CTRL_SCOPE` text COLLATE utf8_bin NOT NULL,
  `CTRL_FILE_ID` int(11) DEFAULT NULL,
  `CTRL_CREATE_DATE` datetime NOT NULL,
  `CTRL_CREATE_BY` int(11) NOT NULL,
  `CTRL_MODIFY_DATE` datetime DEFAULT NULL,
  `CTRL_MODIFY_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`CTRL_ID`),
  KEY `CTRL_CREATE_BY` (`CTRL_CREATE_BY`),
  KEY `CTRL_MODIFY_BY` (`CTRL_MODIFY_BY`),
  KEY `CTRL_FILE_ID` (`CTRL_FILE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS `ctrl_hist` (
  `CTRL_HIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CTRL_HIST_CTRL_ID` int(11) NOT NULL,
  `CTRL_YEAR` int(11) NOT NULL,
  `CTRL_NAME` varchar(128) COLLATE utf8_bin NOT NULL,
  `CTRL_INSTITUTION` varchar(128) COLLATE utf8_bin NOT NULL,
  `CTRL_DATE_START` date NOT NULL,
  `CTRL_DATE_END` date NOT NULL,
  `CTRL_SCOPE` text COLLATE utf8_bin NOT NULL,
  `CTRL_MODIFY_DATE` datetime NOT NULL,
  `CTRL_MODIFY_BY` int(11) NOT NULL,
  PRIMARY KEY (`CTRL_HIST_ID`),
  KEY `CTRL_HIST_CTRL_ID` (`CTRL_HIST_CTRL_ID`),
  KEY `CTRL_MODIFY_BY` (`CTRL_MODIFY_BY`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=3 ;

--
-- Ograniczenia dla zrzutów tabel
--

--
-- Ograniczenia dla tabeli `ctrl_hist`
--
ALTER TABLE `ctrl_hist`
  ADD CONSTRAINT `ctrl_hist_ibfk_2` FOREIGN KEY (`CTRL_MODIFY_BY`) REFERENCES `usr` (`USR_ID`),
  ADD CONSTRAINT `ctrl_hist_ibfk_1` FOREIGN KEY (`CTRL_HIST_CTRL_ID`) REFERENCES `ctrl` (`CTRL_ID`) ON DELETE CASCADE;

--
-- Wyzwalacze `ctrl`
--
DROP TRIGGER IF EXISTS `AddHistoryExternalControlRecord`;
DELIMITER //
CREATE TRIGGER `AddHistoryExternalControlRecord` AFTER UPDATE ON `ctrl`
 FOR EACH ROW BEGIN	
	
	INSERT INTO `ctrl_hist` (`CTRL_HIST_CTRL_ID`, `CTRL_YEAR`, `CTRL_NAME`, `CTRL_INSTITUTION`, `CTRL_DATE_START`, `CTRL_DATE_END`, 
	`CTRL_SCOPE`, `CTRL_MODIFY_DATE`, `CTRL_MODIFY_BY`)
	VALUES
	(
		OLD.CTRL_ID
		,OLD.CTRL_YEAR
		,OLD.CTRL_NAME
		,OLD.CTRL_INSTITUTION
		,OLD.CTRL_DATE_START
		,OLD.CTRL_DATE_END
		,OLD.CTRL_SCOPE
		,NEW.CTRL_MODIFY_DATE 	 	 	 	 	 	
		,NEW.CTRL_MODIFY_BY
	);
	
END
//
DELIMITER ;

--
-- Ograniczenia dla zrzutów tabel
--

--
-- Ograniczenia dla tabeli `ctrl`
--
ALTER TABLE `ctrl`
  ADD CONSTRAINT `ctrl_ibfk_1` FOREIGN KEY (`CTRL_FILE_ID`) REFERENCES `fil` (`FIL_ID`),
  ADD CONSTRAINT `ctrl_ibfk_2` FOREIGN KEY (`CTRL_CREATE_BY`) REFERENCES `usr` (`USR_ID`),
  ADD CONSTRAINT `ctrl_ibfk_3` FOREIGN KEY (`CTRL_MODIFY_BY`) REFERENCES `usr` (`USR_ID`);
