INSERT INTO  `bonafide_bip`.`inf` (
`INF_ID` ,
`INF_NAME` ,
`INF_CONTENT` ,
`INF_OBLIGATORY` ,
`INF_SHOW` ,
`INF_BIP` ,
`INF_SIT_ID` ,
`INF_TYPE` ,
`INF_INF_ID` ,
`INF_SHOW_PRJ_CAT` ,
`INF_SHOW_FILE_CAT` ,
`INF_SHOW_FIN_TYPE` ,
`INF_SHOW_CTRL` ,
`INF_CREATE_DATE` ,
`INF_CREATE_BY` ,
`INF_MODIFY_DATE` ,
`INF_MODIFY_BY`
)
VALUES (
NULL ,  'Jesteœmy Organizacj¹ Po¿ytku Publicznego',  NULL,  '0',  '1',  '1',  '1',  '1', NULL , NULL , NULL , NULL ,  '0',  '2013-02-27 12:28:37',  '1', NULL , NULL
);


DROP TRIGGER IF EXISTS AddHistoryInformationRecord $$

CREATE TRIGGER AddHistoryInformationRecord AFTER UPDATE on `inf`
FOR EACH ROW BEGIN	
	
	IF OLD.INF_CONTENT <> NEW.INF_CONTENT THEN
	
	INSERT INTO `inf_hist` (`INF_HIST_INF_ID`, `INF_CONTENT`, `INF_MODIFY_DATE`, `INF_MODIFY_BY`)
	VALUES
	(
		OLD.INF_ID
		,OLD.INF_CONTENT
		,NEW.INF_MODIFY_DATE 	 	 	 	 	 	
		,NEW.INF_MODIFY_BY
	);
	
	END IF;
	
END$$

(Delimiter: $$)


DROP TRIGGER IF EXISTS `AddHistoryExternalControlRecord`;
DELIMITER //
CREATE TRIGGER `AddHistoryExternalControlRecord` AFTER UPDATE ON `ctrl`
 FOR EACH ROW BEGIN	
	
	IF OLD.CTRL_YEAR <> NEW.CTRL_YEAR OR OLD.CTRL_NAME <> NEW.CTRL_NAME OR OLD.CTRL_INSTITUTION <> NEW.CTRL_INSTITUTION OR 
		OLD.CTRL_DATE_START <> NEW.CTRL_DATE_START OR OLD.CTRL_DATE_END <> NEW.CTRL_DATE_END OR OLD.CTRL_SCOPE <> NEW.CTRL_SCOPE THEN
	INSERT INTO `ctrl_hist` (`CTRL_HIST_CTRL_ID`, `CTRL_YEAR`, `CTRL_NAME`, `CTRL_INSTITUTION`, `CTRL_DATE_START`, `CTRL_DATE_END`, 
	`CTRL_SCOPE`, `CTRL_MODIFY_DATE`, `CTRL_MODIFY_BY`)
	VALUES
	(
		OLD.CTRL_ID
		,OLD.CTRL_YEAR
		,OLD.CTRL_NAME
		,OLD.CTRL_INSTITUTION
		,OLD.CTRL_DATE_START
		,OLD.CTRL_DATE_END
		,OLD.CTRL_SCOPE
		,NEW.CTRL_MODIFY_DATE 	 	 	 	 	 	
		,NEW.CTRL_MODIFY_BY
	);
	END IF;
	
END
//
DELIMITER ;


DROP TRIGGER IF EXISTS AddHistoryProjectRecord $$

CREATE TRIGGER AddHistoryProjectRecord AFTER UPDATE on `prj`
FOR EACH ROW BEGIN	
	
	IF OLD.PRJ_NAME <> NEW.PRJ_NAME OR OLD.PRJ_DESCRIPTION <> NEW.PRJ_DESCRIPTION OR OLD.PRJ_SHORT_DESCRIPTION <> NEW.PRJ_SHORT_DESCRIPTION OR
		OLD.PRJ_AMOUNT_DONATION <> NEW.PRJ_AMOUNT_DONATION OR OLD.PRJ_AMOUNT_PUBLIC <> NEW.PRJ_AMOUNT_PUBLIC OR OLD.PRJ_SOURCES <> NEW.PRJ_SOURCES OR
		OLD.PRJ_CAT <> NEW.PRJ_CAT THEN
	INSERT INTO `prj_hist` (`PRJ_HIST_PRJ_ID`, `PRJ_NAME`, `PRJ_DESCRIPTION`, `PRJ_SHORT_DESCRIPTION`, `PRJ_AMOUNT_DONATION`, `PRJ_AMOUNT_PUBLIC`, 
	`PRJ_SOURCES`, `PRJ_CAT`, `PRJ_MODIFY_DATE`, `PRJ_MODIFY_BY`)
	VALUES
	(
		OLD.PRJ_ID
		,OLD.PRJ_NAME
		,OLD.PRJ_DESCRIPTION
		,OLD.PRJ_SHORT_DESCRIPTION
		,OLD.PRJ_AMOUNT_DONATION
		,OLD.PRJ_AMOUNT_PUBLIC
		,OLD.PRJ_SOURCES
		,OLD.PRJ_CAT
		,NEW.PRJ_MODIFY_DATE 	 	 	 	 	 	
		,NEW.PRJ_MODIFY_BY
	);
	END IF;
	
END$$

(Delimiter: $$)


DROP TRIGGER IF EXISTS AddHistoryFinanceRecord $$

CREATE TRIGGER AddHistoryFinanceRecord AFTER UPDATE on `fin`
FOR EACH ROW BEGIN	
	
	IF OLD.FIN_AMOUNT <> NEW.FIN_AMOUNT THEN
	INSERT INTO `fin_hist` (`FIN_HIST_FIN_ID`, `FIN_AMOUNT`, `FIN_MODIFY_DATE`, `FIN_MODIFY_BY`)
	VALUES
	(
		OLD.FIN_ID
		,OLD.FIN_AMOUNT
		,NEW.FIN_MODIFY_DATE 	 	 	 	 	 	
		,NEW.FIN_MODIFY_BY
	);
	END IF;
	
END$$

(Delimiter: $$)

DROP TRIGGER IF EXISTS `AddHistoryFileRecord`;
DELIMITER //
CREATE TRIGGER `AddHistoryFileRecord` AFTER UPDATE ON `fil`
 FOR EACH ROW BEGIN	
	
	IF OLD.FIL_CONTENT <> NEW.FIL_CONTENT THEN
	INSERT INTO `fil_hist` (`FIL_HIST_FIL_ID`, `FIL_NAME`, `FIL_CONTENT`, `FIL_MODIFY_DATE`, `FIL_MODIFY_BY`)
	VALUES
	(
		OLD.FIL_ID
		,OLD.FIL_NAME
		,OLD.FIL_CONTENT
		,NEW.FIL_MODIFY_DATE 	 	 	 	 	 	
		,NEW.FIL_MODIFY_BY
	);
	END IF;
	
END
//
DELIMITER ;


ALTER TABLE  `prj_hist` DROP FOREIGN KEY  `prj_hist_ibfk_1` ;

ALTER TABLE  `prj_hist` ADD FOREIGN KEY (  `PRJ_HIST_PRJ_ID` ) REFERENCES  `bonafide_bip`.`prj` (
`PRJ_ID`
) ON DELETE CASCADE ;



ALTER TABLE  `fin_hist` DROP FOREIGN KEY  `fin_hist_ibfk_1` ;

ALTER TABLE  `fin_hist` ADD FOREIGN KEY (  `FIN_HIST_FIN_ID` ) REFERENCES  `bonafide_bip`.`fin` (
`FIN_ID`
) ON DELETE CASCADE ;