ALTER TABLE  `prj` ADD  `PRJ_CREATE_DATE` DATETIME NOT NULL ,
ADD  `PRJ_CREATE_BY` INT NOT NULL ,
ADD  `PRJ_MODIFY_DATE` DATETIME NULL ,
ADD  `PRJ_MODIFY_BY` INT NULL;

update `prj` set `PRJ_CREATE_BY` = 1 , `PRJ_CREATE_DATE` = NOW(), `PRJ_MODIFY_BY` = NULL, `PRJ_MODIFY_DATE` = NULL;

ALTER TABLE  `prj` ADD INDEX (  `PRJ_CREATE_BY` );
ALTER TABLE  `prj` ADD INDEX (  `PRJ_MODIFY_BY` );

ALTER TABLE  `prj` ADD FOREIGN KEY (  `PRJ_CREATE_BY` ) REFERENCES `usr` (`USR_ID`);
ALTER TABLE  `prj` ADD FOREIGN KEY (  `PRJ_MODIFY_BY` ) REFERENCES `usr` (`USR_ID`);

CREATE TABLE IF NOT EXISTS `prj_hist` (
  `PRJ_HIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRJ_HIST_PRJ_ID` int(11) NOT NULL,
  `PRJ_NAME` varchar(256) COLLATE utf8_bin NOT NULL DEFAULT ' ',
  `PRJ_DESCRIPTION` varchar(512) COLLATE utf8_bin NOT NULL,
  `PRJ_SHORT_DESCRIPTION` varchar(256) COLLATE utf8_bin DEFAULT NULL,
  `PRJ_AMOUNT_DONATION` double DEFAULT NULL,
  `PRJ_AMOUNT_PUBLIC` double DEFAULT NULL,
  `PRJ_SOURCES` varchar(512) COLLATE utf8_bin NOT NULL,
  `PRJ_CAT` int(11) NOT NULL COMMENT '1 - CURRENT, 2 - PASSED',
  `PRJ_MODIFY_DATE` DATETIME NULL ,
  `PRJ_MODIFY_BY` INT NULL,
  PRIMARY KEY (`PRJ_HIST_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;


/* History Trigger */
DROP TRIGGER IF EXISTS AddHistoryProjectRecord $$

CREATE TRIGGER AddHistoryProjectRecord AFTER UPDATE on `prj`
FOR EACH ROW BEGIN	
	
	INSERT INTO `prj_hist` (`PRJ_HIST_PRJ_ID`, `PRJ_NAME`, `PRJ_DESCRIPTION`, `PRJ_SHORT_DESCRIPTION`, `PRJ_AMOUNT_DONATION`, `PRJ_AMOUNT_PUBLIC`, 
	`PRJ_SOURCES`, `PRJ_CAT`, `PRJ_MODIFY_DATE`, `PRJ_MODIFY_BY`)
	VALUES
	(
		OLD.PRJ_ID
		,OLD.PRJ_NAME
		,OLD.PRJ_DESCRIPTION
		,OLD.PRJ_SHORT_DESCRIPTION
		,OLD.PRJ_AMOUNT_DONATION
		,OLD.PRJ_AMOUNT_PUBLIC
		,OLD.PRJ_SOURCES
		,OLD.PRJ_CAT
		,NEW.PRJ_MODIFY_DATE 	 	 	 	 	 	
		,NEW.PRJ_MODIFY_BY
	);
	
END$$

(Delimiter: $$)


ALTER TABLE  `prj_hist` ADD INDEX (  `PRJ_HIST_PRJ_ID` );
ALTER TABLE  `prj_hist` ADD FOREIGN KEY (  `PRJ_HIST_PRJ_ID` ) REFERENCES `prj` (`PRJ_ID`);

ALTER TABLE  `prj_hist` ADD INDEX (  `PRJ_MODIFY_BY` );
ALTER TABLE  `prj_hist` ADD FOREIGN KEY (  `PRJ_MODIFY_BY` ) REFERENCES  `usr` (`USR_ID`);

/* metryczka dokumentu */

ALTER TABLE  `fil` ADD  `FIL_INFO_CREATED_BY` VARCHAR( 256 ) NULL ,
ADD  `FIL_INFO_CREATEDATE` DATETIME NULL;

ALTER TABLE  `fil` ADD FOREIGN KEY (  `FIL_CREATE_BY` ) REFERENCES `usr` (`USR_ID`);
ALTER TABLE  `fil` ADD FOREIGN KEY (  `FIL_MODIFY_BY` ) REFERENCES `usr` (`USR_ID`);

/* finanse historia */

ALTER TABLE  `fin` ADD  `FIN_CREATE_DATE` DATETIME NOT NULL ,
ADD  `FIN_CREATE_BY` INT NOT NULL ,
ADD  `FIN_MODIFY_DATE` DATETIME NULL ,
ADD  `FIN_MODIFY_BY` INT NULL;

update `fin` set `FIN_CREATE_BY` = 1 , `FIN_CREATE_DATE` = NOW(), `FIN_MODIFY_BY` = NULL, `FIN_MODIFY_DATE` = NULL;


ALTER TABLE  `fin` ADD INDEX (  `FIN_CREATE_BY` );
ALTER TABLE  `fin` ADD INDEX (  `FIN_MODIFY_BY` );

ALTER TABLE  `fin` ADD FOREIGN KEY (  `FIN_CREATE_BY` ) REFERENCES `usr` (`USR_ID`);
ALTER TABLE  `fin` ADD FOREIGN KEY (  `FIN_MODIFY_BY` ) REFERENCES `usr` (`USR_ID`);

ALTER TABLE  `fin_hist` DROP FOREIGN KEY  `fin_hist_ibfk_1` ;
ALTER TABLE  `fin_hist` CHANGE  `FIN_ID`  `FIN_HIST_FIN_ID` INT( 11 ) NOT NULL;

ALTER TABLE  `fin_hist` ADD  `FIN_MODIFY_DATE` DATETIME NOT NULL ,
ADD  `FIN_MODIFY_BY` INT NOT NULL ,
ADD INDEX (  `FIN_MODIFY_BY` );

ALTER TABLE  `fin_hist` ADD FOREIGN KEY (  `FIN_HIST_FIN_ID` ) REFERENCES `fin` (`FIN_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE  `fin_hist` ADD FOREIGN KEY (  `FIN_MODIFY_BY` ) REFERENCES `usr` (`USR_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT ;

/* Finance History Trigger */
DROP TRIGGER IF EXISTS AddHistoryFinanceRecord $$

CREATE TRIGGER AddHistoryFinanceRecord AFTER UPDATE on `fin`
FOR EACH ROW BEGIN	
	
	INSERT INTO `fin_hist` (`FIN_HIST_FIN_ID`, `FIN_AMOUNT`, `FIN_MODIFY_DATE`, `FIN_MODIFY_BY`)
	VALUES
	(
		OLD.FIN_ID
		,OLD.FIN_AMOUNT
		,NEW.FIN_MODIFY_DATE 	 	 	 	 	 	
		,NEW.FIN_MODIFY_BY
	);
	
END$$

(Delimiter: $$)
