ALTER TABLE  `fin` ADD  `FIN_CURRENCY` INT NOT NULL DEFAULT  '1' AFTER  `FIN_AMOUNT`;
ALTER TABLE  `fin_hist` ADD  `FIN_CURRENCY` INT NOT NULL DEFAULT  '1' AFTER  `FIN_AMOUNT`;
ALTER TABLE  `prj` ADD  `PRJ_DONATION_CURRENCY` INT NULL DEFAULT NULL AFTER  `PRJ_AMOUNT_DONATION`;
ALTER TABLE  `prj` ADD  `PRJ_PUBLIC_CURRENCY` INT NULL DEFAULT NULL AFTER  `PRJ_AMOUNT_PUBLIC`;
ALTER TABLE  `prj_hist` ADD  `PRJ_DONATION_CURRENCY` INT NULL DEFAULT NULL AFTER  `PRJ_AMOUNT_DONATION`;
ALTER TABLE  `prj_hist` ADD  `PRJ_PUBLIC_CURRENCY` INT NULL DEFAULT NULL AFTER  `PRJ_AMOUNT_PUBLIC`;