DROP TRIGGER IF EXISTS AddHistoryFileRecord $$

CREATE TRIGGER AddHistoryFileRecord AFTER UPDATE on `fil`
FOR EACH ROW BEGIN	
	
	INSERT INTO `fil_hist` (`FIL_HIST_FIL_ID`, `FIL_NAME`, `FIL_CONTENT`, `FIL_MODIFY_DATE`, `FIL_MODIFY_BY`)
	VALUES
	(
		OLD.FIL_ID
		,OLD.FIL_NAME
		,OLD.FIL_CONTENT
		,NEW.FIL_MODIFY_DATE 	 	 	 	 	 	
		,NEW.FIL_MODIFY_BY
	);
	
END$$

(Delimiter: $$)


